### ISSUE TITLE
Error generating files

### ISSUE THREAD

**Issue by Terule** [Oluwasegun-AA/md-generator#38]
**Describe the bug**
Can't create MD file

**To Reproduce**
1. md-generator create
2. select readme.md
3. go through the options
4. error at the end

**Expected behavior**
MD created

**Screenshots**
![lmaterial-ui](https://user-images.githubusercontent.com/20166561/225905345-45d62a66-4f99-4b1a-a76e-efdd76f09086.png)

**Desktop (please complete the following information):**
 - Windows 11 - latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Oluwasegun-AA** [comment]
@Terule, Thank you for flagging this.
This error was because no option was selected from the listed options.
The following key are used to interact with the options
-  `space` key is used to select an option
-  key `a` is used to toggle all
-   key `i` to invert selection

This issue has been resolved in v0.5.3

Thanks
